language: python

python:
  - "2.7"

os:
  - linux
  - osx

cache: pip

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi

install:
  - pip install codecov

script:
  - coverage run setup.py --tests

after_success:
  - codecov